use_frameworks!

target 'TBParseConversion_Example' do
    pod 'TBParse/Conversion', :path => '../'
end

target 'TBParse_Example' do
  pod 'TBParse', :path => '../'

  target 'TBParse_Tests' do
    inherit! :search_paths

    
  end
end
